# Generated by Django 5.2.7 on 2025-11-15 13:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumFeature',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='null', max_length=200)),
                ('feature_type', models.CharField(choices=[('featured_listing', 'Featured Job Listing'), ('advanced_tools', 'Advanced Recruitment Tools'), ('bulk_posting', 'Bulk Job Posting'), ('analytics', 'Advanced Analytics')], max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.IntegerField(help_text='Duration in days (0 for one-time)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='SelectedFeature',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('purchased_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.premiumfeature')),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('feature', 'purchaser')},
            },
        ),
    ]
