# Generated by Django 5.2.7 on 2025-11-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_premiumfeature_user_alter_premiumfeature_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumfeature',
            name='user',
        ),
    ]
