# Generated by Django 5.2.7 on 2025-11-03 11:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_remove_jobseekerprofile_user_applicants_and_more'),
        ('job_seeker', '0003_appliedjobs_delete_savedjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedjobs',
            old_name='job_seeker',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='appliedjobs',
            unique_together={('user', 'job')},
        ),
    ]
