# Generated by Django 5.2.7 on 2025-11-03 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0004_rename_job_seeker_appliedjobs_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appliedjobs',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='appliedjobs',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='appliedjobs',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applied_jobs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
