# Generated by Django 5.2.7 on 2025-11-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0005_alter_appliedjobs_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('interview_scheduled', 'Interview Scheduled'), ('offered', 'Offered'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
    ]
