# Generated by Django 5.2.7 on 2025-11-04 02:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0010_delete_applicants'),
        ('job_seeker', '0006_appliedjobs_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appliedjobs',
            options={'ordering': ['-applied_at'], 'verbose_name': 'Applied Job', 'verbose_name_plural': 'Applied Jobs'},
        ),
        migrations.AlterUniqueTogether(
            name='appliedjobs',
            unique_together={('user', 'job')},
        ),
    ]
