# Generated by Django 5.2.7 on 2025-11-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0007_alter_appliedjobs_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='use_profile_resume',
            field=models.BooleanField(default=False),
        ),
    ]
