# Generated by Django 5.2.7 on 2025-11-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='job_seeker',
        ),
        migrations.DeleteModel(
            name='EmployerProfile',
        ),
        migrations.DeleteModel(
            name='JobSeekerProfile',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
