# Generated by Django 5.2.7 on 2025-11-03 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_alter_job_employer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='employer',
            new_name='user',
        ),
    ]
