# Generated by Django 5.2.7 on 2025-11-03 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_rename_employer_job_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 3, 9, 44, 44, 350332, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
