# Generated by Django 5.2.7 on 2025-11-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_remove_jobseekerprofile_user_applicants_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='applicants',
        ),
    ]
