# Generated by Django 5.2.7 on 2026-02-06 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0012_alter_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(blank=True, default='General', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='employer.jobcategory'),
        ),
    ]
